- name: Install prerequisites
  ansible.builtin.dnf:
    name:
      - policycoreutils
      - openssh-clients
      - perl
      - postfix
      - cronie
    state: present

- name: Import all GitLab GPG keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - https://packages.gitlab.com/gpgkey/gpg.key
    - https://packages.gitlab.com/gpgkey/gitlab/3D645A26AB9FBD22.pub.gpg
    - https://packages.gitlab.com/gpgkey/gitlab/CB947AD886C8E8FD.pub.gpg

- name: Add GitLab CE binary repository
  ansible.builtin.yum_repository:
    name: gitlab_gitlab-ce
    description: gitlab_gitlab-ce
    baseurl: "https://packages.gitlab.com/gitlab/gitlab-ce/amazon/2023/$basearch"
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300
    state: present

- name: Add GitLab CE source repository
  ansible.builtin.yum_repository:
    name: gitlab_gitlab-ce-source
    description: gitlab_gitlab-ce-source
    baseurl: "https://packages.gitlab.com/gitlab/gitlab-ce/amazon/2023/SRPMS"
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300
    state: present

- name: Install GitLab CE
  ansible.builtin.dnf:
    name: "gitlab-ce-18.11.2-ce.0.amazon2023"
    state: present

- name: Ensure GitLab is enabled and started
  ansible.builtin.service:
    name: gitlab-runsvdir
    state: started
    enabled: true
  no_log: true
