- name: Setup common configurations
  hosts: all
  become: yes
  roles:
    - common
  tags: common

- name: Setup PostgreSQL 17
  hosts: pgsql
  become: yes
  roles:
    - pgsql
  tags: pgsql

- name: Setup Valkey
  hosts: valkey
  become: yes
  roles:
    - valkey
  tags: valkey

- name: Setup GitLab CE
  hosts: gitlab
  become: yes
  roles:
    - gitlab
  tags: gitlab

- name: Setup Jenkins
  hosts: jenkins_vm
  become: yes
  roles:
    - jenkins
  tags: jen

- name: Setup Docker
  hosts: swarm
  become: yes
  roles:
    - docker
  tags: docker
