all:
  hosts:
    gitlab_vm:
      ansible_host: 192.168.56.5
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3.9
    jenkins_vm:
      ansible_host: 192.168.56.6
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3.9
    swarm1_vm:
      ansible_host: 192.168.56.11
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3.9
    swarm2_vm:
      ansible_host: 192.168.56.12
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3.9
    swarm3_vm:
      ansible_host: 192.168.56.13
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3.9
  children:
    pgsql:
      hosts: {}
    valkey:
      hosts: {}
    gitlab:
      hosts:
        gitlab_vm: {}
    jenkins:
      hosts:
        jenkins_vm:
    swarm:
      children:
        managers:
          hosts:
            swarm1_vm: {}
            swarm2_vm: {}
            swarm3_vm: {}
        workers:
          hosts: {}
