all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3.12
    gitlab_vm:
      ansible_host: 192.168.56.5
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3.9
    jenkins_vm:
      ansible_host: 192.168.56.6
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3.9
    swarm-node1:
      ansible_host: 192.168.56.11
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3.9
    swarm-node2:
      ansible_host: 192.168.56.12
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3.9
    swarm-node3:
      ansible_host: 192.168.56.13
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3.9
    elk1:
      ansible_host: 192.168.56.21
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3.9
    elk2:
      ansible_host: 192.168.56.22
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3.9
    elk3:
      ansible_host: 192.168.56.23
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python3.9
    elk4:
      ansible_host: 192.168.56.24
      ansible_user: vagrant
      ansible_python_interpreter: /usr/bin/python3.12
    nexus-node:
      ansible_host: 192.168.56.30
      ansible_user: vagrant
      ansible_python_interpreter: /usr/bin/python3.12
  children:
    gitlab:
      hosts:
        gitlab_vm: {}
    jenkins:
      hosts:
        jenkins_vm:
    nexus:
      hosts:
        nexus-node: {}
    swarm:
      children:
        managers:
          hosts:
            swarm-node1: {}
            swarm-node2: {}
            swarm-node3: {}
        workers:
          hosts: {}
    elastic:
      children:
        esearch:
          hosts:
            elk1: {}
        kibana:
          hosts:
            elk2: {}
        logstash:
          hosts:
            elk2: {}
    pgsql:
      hosts:
        elk3: {}
        elk4: {}
