global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scheme: "http"
    static_configs:
      - targets: ["prom.begoingto.test"]
    # basic_auth:
    #   username: "{{ prometheus_user }}"
    #   password: "{{ prometheus_password }}"

  - job_name: "swarm-node2"
    metrics_path: /metrics
    scheme: "http"
    static_configs:
      - targets: ["swarm-node2.begoingto.test"]
