input {
  beats {
    port => 5044
  }
}

filter {
  if [log][file][path] =~ "request.log" {
    grok {
      match => {
        "message" => "%{IPORHOST:client_ip} - %{DATA:user} \[%{HTTPDATE:log_timestamp}\] \"%{WORD:http_method} %{DATA:url} HTTP/%{NUMBER:http_version}\" %{NUMBER:status_code:int} %{NUMBER:bytes:int}"
      }
    }
    date {
      match => ["log_timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
      target => "@timestamp"
    }
    mutate {
      add_field => { "log_type" => "nexus_request" }
    }
  }
  else if [log][file][path] =~ "audit.log" {
    mutate {
      add_field => { "log_type" => "nexus_audit" }
    }
  }
  else if [log][file][path] =~ "karaf.log" {
    mutate {
      add_field => { "log_type" => "nexus_karaf" }
    }
  }
  else if [log][file][path] =~ "nexus.log" {
    mutate {
      add_field => { "log_type" => "nexus_app" }
    }
  }
  else {
    mutate {
      add_field => { "log_type" => "nexus_other" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["192.168.56.21:9200"]
		index => "nexus-logs-%{+YYYY.MM.dd}"
    user => "admin"
    password => "Admin@123"
    ssl_certificate_authorities => ['/etc/logstash/certs/elastic-stack-ca.pem']
	}

  stdout { codec => rubydebug }
}
