Vagrant.configure("2") do |config|
  config.vm.box = "bento/amazonlinux-2023"
  config.vm.box_version = "202510.26.0"
  config.vm.network "private_network", ip: "192.168.56.5"
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "8192"
		vb.cpus = 6
	end
	config.vm.provision "shell", inline: <<-SHELL
		sudo dnf update -y
		sudo dnf install network-scripts htop -y
		sudo dnf upgrade --releasever=2023.10.20260302 -y
		SHELL
end
