Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "jen-node#{i}" do |node|
			node.vm.hostname = "jen-node#{i}"
      node.vm.box = "bento/amazonlinux-2023"
      node.vm.box_version = "202510.26.0"
      node.vm.network "private_network", ip: "192.168.56.#{5 + i}"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
      end
    end
  end
end
