elasticsearch_version: "9.3.2"
cluster_name: "elastic-dev"
heap_size: "1g"

elastic_user: "elastic"
elastic_user_pass: "Admin@123"

ssl_dir: "/etc/elasticsearch/ssl"
ssl_filename: "elasticsearch"

ca_key_pass: "changeit"
keystore_pass: "admin123"
force_ca: false

kibana_certs_dir: "/etc/kibana/certs"
kibana_ssl_dir: "/etc/kibana/ssl"
kibana_ssl_filename: "kibana"

logstash_dir: "/etc/logstash"
logstash_ssl_dir: "/etc/logstash/ssl"
logstash_ssl_filename: "logstash"
