- name: Debug os family, distribution, and distribution major version
  ansible.builtin.debug:
    msg: "OS Family: {{ ansible_facts.os_family }}\nDistribution: {{ ansible_facts.distribution }}\nDistribution Major Version: {{ ansible_facts.distribution_major_version }}\n"

- name: Set timezone to Asia/Phnom Penh
  ansible.builtin.timezone:
    name: Asia/Phnom_Penh

- name: Update apt cache
  when: ansible_facts.os_family == "Debian"
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgradable packages
  when: ansible_facts.os_family == "Debian" and upgradable is defined
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes # This is equivalent to "apt upgrade"
    autoremove: yes # Optional: removes unused dependencies (like apt autoremove)
    autoclean: yes # Optional: cleans the local repository
    cache_valid_time: 3600 # Optional: only run update_cache if older than 1 hour

- name: Update yum cache
  when: ansible_facts.os_family == "RedHat"
  ansible.builtin.dnf:
    update_cache: yes

- name: Amazon linux 2023
  when: ansible_facts.distribution == "Amazon" and ansible_facts.distribution_major_version == "2023"
  block:
    - name: Install network-scripts and htop
      ansible.builtin.dnf:
        name:
          - network-scripts
          - htop
        state: present

    - name: "Upgrade Amazon Linux 2023 to specific release version {{ releasever }}"
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes
        releasever: "{{ releasever }}"
        allow_downgrade: yes
      become: true
