- name: Check if node is already part of a Swarm
  community.docker.docker_swarm_info:
  register: swarm_info
  ignore_errors: true

- name: Debug groups
  ansible.builtin.debug:
    msg: "Groups: {{ groups['managers'] }}"

- name: Initialize Swarm on the first manager only (manager1)
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ ansible_host }}"
  run_once: true
  when: inventory_hostname == groups['managers'][0] and swarm_info.swarm is not defined

- name: Get Swarm manager join token
  ansible.builtin.command: docker swarm join-token manager -q
  register: manager_token
  run_once: true
  changed_when: false
  when: inventory_hostname == groups['managers'][0]

# - name: Get Swarm worker join token (optional for workers)
#   ansible.builtin.command: docker swarm join-token worker -q
#   register: worker_token
#   run_once: true
#   changed_when: false
#   when: inventory_hostname == groups['managers'][0]

- name: Join additional managers to the Swarm
  community.docker.docker_swarm:
    state: join
    join_token: "{{ hostvars[groups['managers'][0]]['manager_token']['stdout'] }}"
    advertise_addr: "{{ ansible_host }}"
    remote_addrs:
      - "{{ hostvars[groups['managers'][0]]['ansible_host'] }}:2377"
  when:
    - inventory_hostname != groups['managers'][0]
    - swarm_info.swarm is not defined

- name: Verify Swarm status
  ansible.builtin.command: docker node ls
  register: node_list
  changed_when: false
  run_once: true

- name: Show Swarm nodes
  ansible.builtin.debug:
    msg: "{{ node_list.stdout_lines }}"
  run_once: true
