- name: Create Traefik network
  community.docker.docker_network:
    name: "{{ traefik_network_name }}"
    driver: overlay
    state: present

- name: Upload traefik configuration file
  become: true
  ansible.builtin.template:
    src: traefik.yml
    dest: /opt/traefik.yml

- name: Create Swarm services for Traefik
  when: inventory_hostname == swarm_leader
  register: service_result
  community.docker.docker_swarm_service:
    name: traefik
    image: "traefik:{{ traefik_version }}"
    replicas: 2
    mounts:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /opt/traefik.yml
        target: /etc/traefik/traefik.yml
    networks:
      - name: "{{ traefik_network_name }}"
      - name: "host"
    publish:
      - published_port: 80
        target_port: 80
      - published_port: 443
        target_port: 443
      - published_port: 8080
        target_port: 8080
    update_config:
      parallelism: 1
      delay: 10s
      failure_action: rollback
      order: start-first
    restart_config:
      condition: on-failure
      delay: 5s
      max_attempts: 3
    force_update: "{{ force_redeploy | default(false) | bool }}"

- name: Show if service was updated/redeployed
  when: inventory_hostname == swarm_leader
  ansible.builtin.debug:
    msg: "Service changed: {{ service_result.changed }}"
