- name: include tasks for repository setup
  ansible.builtin.include_tasks: repo.yml

- name: Install Kibana
  become: true
  ansible.builtin.dnf:
    name: kibana-{{ elasticsearch_version }}
    state: present
    update_cache: yes
    enablerepo: elasticsearch

- name: Configure kibana.yml (small VM + cluster friendly)
  become: true
  ansible.builtin.copy:
    dest: /etc/kibana/kibana.yml
    backup: true
    content: |
      server.host: "0.0.0.0"
      server.port: 5601

      server.ssl.enabled: true
      server.ssl.keystore.path: "/etc/kibana/certs/kibana-server.p12"
      server.ssl.keystore.password: ""

      # xpack.encryptedSavedObjects.encryptionKey: b6747239038cda5d3b27f57455503727b15fd38039b8440584bec469628feece
      # xpack.reporting.encryptionKey: 4a26a3037debbf61f2bffd8aae956099c5ab2c5c49eb0fd97260b6036931d99a
      # xpack.security.encryptionKey: 2d6c3820ef2e805a0c6e5d8c1544a9be76ac1ed669a8961ca5229b428cc3fe1f
      # Enables you to specify a file where Kibana stores log output.
      logging:
        appenders:
          file:
            type: file
            fileName: /var/log/kibana/kibana.log
            layout:
              type: json
        root:
          appenders:
            - default
            - file

      pid.file: /run/kibana/kibana.pid
      # Point to your Elasticsearch (use elasticsearch username/password if security is on)
      elasticsearch.hosts: ["https://{{ hostvars['elastic-node1']['ansible_host'] }}:9200"]
      elasticsearch.ssl.certificateAuthorities: ["/etc/kibana/certs/elastic-stack-ca.pem"]
      elasticsearch.ssl.verificationMode: certificate
      elasticsearch.username: "kibana_system"
      elasticsearch.password: "Admin@123"

      # Reduce memory pressure
      server.maxPayload: 1048576
    mode: "0644"
  notify: Restart Kibana

- name: Enable and start Elastic Kibana service
  become: true
  ansible.builtin.systemd:
    name: kibana
    enabled: yes
    state: started
    daemon_reload: yes
  no_log: true
