- name: Install java-21-amazon-corretto
  ansible.builtin.dnf:
    name: java-21-amazon-corretto
    state: present
    update_cache: yes

- name: include tasks for repository setup
  ansible.builtin.include_tasks: repo.yml

- name: Install Logstash
  ansible.builtin.dnf:
    name: logstash-{{ elasticsearch_version }}
    state: present
    update_cache: yes
    enablerepo: elasticsearch

- name: include tasks SSL certificate
  ansible.builtin.include_tasks: logstash-openssl.yml

- name: Configure Logstash (logstash.yml)
  ansible.builtin.template:
    src: logstash.yml.j2
    dest: /etc/logstash/logstash.yml
    mode: "0644"
  notify: Restart Logstash

- name: Enable and start Elastic Logstash service
  ansible.builtin.systemd:
    name: logstash
    enabled: yes
    state: started
    daemon_reload: yes
  no_log: true

# - name: Add plugin logstash-output-elasticsearch
#   ansible.builtin.command: logstash-plugin install logstash-output-elasticsearch
#   args:
#     chdir: /usr/share/logstash/bin
#     creates: /usr/share/logstash/logstash-core/lib/jars/logstash-output-elasticsearch-*.jar
#   notify: Restart Logstash

- name: Copy elasticsearch CA Certificate
  ansible.builtin.copy:
    src: "{{ role_path }}/files/full_{{ ssl_filename }}.pem"
    dest: "{{ logstash_dir  }}/full_{{ ssl_filename }}.pem"
    owner: root
    group: logstash
    mode: "0640"

- name: Add filebeat Logstash input configuration
  ansible.builtin.template:
    src: filebeat-postgres.conf.j2
    dest: "{{ logstash_dir }}/conf.d/filebeat-postgres.conf"
    owner: root
    group: logstash
    mode: "0644"
  notify: Restart Logstash
