- name: include tasks for repository setup
  ansible.builtin.include_tasks: repo.yml

- name: Install Elasticsearch
  ansible.builtin.dnf:
    name: elasticsearch-{{ elasticsearch_version }}
    state: present
    update_cache: yes
    enablerepo: elasticsearch

- name: Set JVM heap size to {{ heap_size }} (safe for 4GB RAM)
  ansible.builtin.blockinfile:
    path: /etc/elasticsearch/jvm.options.d/heap.options
    create: yes
    content: |
      -Xms{{ heap_size }}
      -Xmx{{ heap_size }}
    mode: "0644"
  notify: Restart Elasticsearch

- name: include tasks for SSL certificate generation
  ansible.builtin.include_tasks: openssl.yml

- name: Add HTTP keystore password to Elasticsearch keystore
  when: result_pkcs12.changed
  ansible.builtin.shell: |
    echo "{{ ca_key_pass }}" | /usr/share/elasticsearch/bin/elasticsearch-keystore add -x -f 'xpack.security.http.ssl.keystore.secure_password'
  no_log: true

- name: Configure Elasticsearch (elasticsearch.yml) - First Node
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: "0644"
  notify: Restart Elasticsearch

- name: Increase vm.max_map_count
  ansible.builtin.sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    reload: yes

- name: Set system limits for Elasticsearch
  ansible.builtin.copy:
    dest: /etc/security/limits.d/elasticsearch.conf
    content: |
      elasticsearch soft nofile 65536
      elasticsearch hard nofile 65536
      elasticsearch soft memlock unlimited
      elasticsearch hard memlock unlimited
    mode: "0644"

- name: Enable and start Elasticsearch service
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: yes
    state: started
    daemon_reload: yes
  no_log: true

- name: Wait for Elasticsearch to be up
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 9200
    delay: 10
    timeout: 300
  register: wait_result
  until: wait_result is success
