---
- name: Configure Elastic Stack ELK
  hosts: elastic
  become: true
  gather_facts: false
  tasks:
    - name: Import task to create elastic kibana
      ansible.builtin.import_role:
        name: elastic
        tasks_from: kibana.yml
      tags: kibana

    - name: Import task to create elastic logstash
      ansible.builtin.import_role:
        name: elastic
        tasks_from: logstash.yml
      tags: logstash

    - name: Import task to create elastic logstash
      ansible.builtin.import_role:
        name: elastic
        tasks_from: config-logstash.yml
      tags: lconfig

    - name: Import task to create elastic filebeat
      ansible.builtin.import_role:
        name: elastic
        tasks_from: filebeat.yml
      tags: filebeat
