- name: Setup common configurations
  hosts: all
  become: true
  roles:
    - common
  tags: common

- name: Setup PostgreSQL 17
  hosts: pgsql
  become: true
  roles:
    - pgsql
  tags: pgsql

- name: Setup Valkey
  hosts: valkey
  become: true
  roles:
    - valkey
  tags: valkey

- name: Setup GitLab CE
  hosts: gitlab
  become: true
  roles:
    - gitlab
  tags: gitlab

- name: Setup Jenkins
  hosts: jenkins_vm
  become: true
  roles:
    - jenkins
  tags: jen

- name: Setup Docker
  hosts: swarm
  gather_facts: false
  become: true
  roles:
    - docker
  tags: docker

- name: Setup Elastic Stack ELK
  hosts: elastic
  become: true
  gather_facts: false
  # strategy: free
  roles:
    - elastic
  tags: elastic
