---
- name: Configure Docker Swarm
  hosts: swarm
  become: false
  gather_facts: false
  tasks:
    - name: Check if node is already part of a Swarm
      community.docker.docker_swarm_info:
        nodes: true
      register: swarm_info
      ignore_errors: true
      tags: always
      no_log: true

    - name: Learder Node
      when: swarm_info.nodes is defined
      ansible.builtin.debug:
        msg: "{{ swarm_info.nodes | selectattr('ManagerStatus', '==', 'Leader') | first }}"
      tags: always

    - name: Set fact current learder node
      ansible.builtin.set_fact:
        swarm_leader: "{{ (swarm_info.nodes | selectattr('ManagerStatus', '==', 'Leader') | first).Hostname }}"
      tags: always

    - name: Import Docker Swarm manager setup tasks
      ansible.builtin.import_role:
        name: docker
        tasks_from: sw-manager.yml
      tags: sw_manager

    - name: Include role docker with task to create traefik network
      ansible.builtin.import_role:
        name: docker
        tasks_from: traefik.yml
      tags: traefik

    - name: Include role docker with task to create nginx service
      ansible.builtin.import_role:
        name: docker
        tasks_from: nginx.yml
      tags: nginx

    - name: Include role docker with task to create prometheus service
      ansible.builtin.import_role:
        name: docker
        tasks_from: prometheus.yml
      tags: prometheus

    - name: Include role docker with task to create grafana service
      ansible.builtin.import_role:
        name: docker
        tasks_from: grafana.yml
      tags: grafana
