---
- name: Configure Traefik
  hosts: swarm
  become: false
  gather_facts: false
  tasks:
    - name: Include role docker with task to create traefik network
      ansible.builtin.import_role:
        name: docker
        tasks_from: traefik.yml
