- name: Restart Elasticsearch
  become: true
  ansible.builtin.systemd:
    name: elasticsearch
    state: restarted

- name: Restart Kibana
  become: true
  ansible.builtin.systemd:
    name: kibana
    state: restarted

- name: Restart Logstash
  become: true
  ansible.builtin.systemd:
    name: logstash
    state: restarted

- name: Restart Filebeat
  become: true
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
